spring.application.name=frontend.api

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
# Warehouse database
app.datasource.warehouse.jdbc-url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${WAREHOUSE_DB_NAME}?currentSchema=public
app.datasource.warehouse.username=${POSTGRES_USER}
app.datasource.warehouse.password=${POSTGRES_PASSWORD}
app.datasource.warehouse.driver-class-name=org.postgresql.Driver
